name: 'GitHub App repository permission parser'
description: 'Parses the yaml body of the issue and adds repositories to GitHub app permissions'
inputs:
  admin_token:
    description: Admin token with access to the organization
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
