name: 'GitHub App repository permission parser'
description: 'Parses the yaml body of the issue and adds repositories to GitHub app permissions'
inputs:
  admin_token:
    description: Admin token with access to the organization
    required: true
  token:
    description: The GitHub actions token
    required: true
    default: ${{ github.token }}
  error_tag_team:
    description: Team to be tagged in case an error is produced
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
