name: 'Capability parser'
description: 'Parses the yaml body of the issue'
inputs:
  admin_token:
    description: Admin token with access to the organization
    required: true
outputs:
  action:
    description: The name of the command
  name:
    description: Name of the capability
  description:
    description: Description of the capability
  owners:
    description: Owners of the capability
  maintainers:
    description: Maintainers of the capability

runs:
  using: 'node12'
  main: 'dist/index.js'
