name: Parse issue
on:
  issues:
    types: [opened]

jobs:
  app-management:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        path: actions

      - name: Parse the issue submitted
        id: issue_parser
        uses: ./actions/app-management
        with:
          admin_token: ${{ secrets.PAT }}
          error_tag_team: refinitiv-org/test
